### ISSUE TITLE
Mix of dutch and english

### ISSUE THREAD

**Issue by cdfa** [svsticky/static-sticky#16]
I noticed there's some hard-coded strings in Dutch throughout the project. I guess for now it would be okay to keep the site in Dutch (even though i'd rather just localize all the strings now) and therefore all the names of the page files are also in Dutch. Apart from that there's also a lot of scattered dutch in variable names and the like throughout the code which looks rather ugly imo. If there's any part of the code that really should be in Dutch for some reason, we should add this to the (currently non-existent) contributing guidelines.

What do you think about this @emielvanrijn ?

**Comment by emielvanrijn** [comment]
You are right, for now, I just hardcoded some string. In the future, we can use the contentful-locale feature for the board to publish in different languages, which is a nice feature. For the rest, we can indeed start localizing the string already. I haven't done so yet because of the MVP that has to be released quickly where locales are no no.1 priority... 

The names of the page files are somewhat in dutch on purpose, as Gatsby automatically generates the slugs based on the folder/filestructure in the pages folder: **vacatures**.jsx becomes svsticky.nl/**vacatures**... We should keep variable names in English, and thus change theme where they are not.

**Comment by cdfa** [comment]
Fixed in [39](https://github.com/svsticky/static-sticky/pull/39)
